/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILockerFactory,
  ILockerFactoryInterface,
} from "../ILockerFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "enum ILockerFactory.Type",
        name: "_type",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "contract IERC20",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_numOfTokens",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_unlockTime",
        type: "uint256",
      },
    ],
    name: "createLcoker",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILockerFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ILockerFactoryInterface {
    return new utils.Interface(_abi) as ILockerFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILockerFactory {
    return new Contract(address, _abi, signerOrProvider) as ILockerFactory;
  }
}
