/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { LaunchPadLib, LaunchPadLibInterface } from "../LaunchPadLib";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensForSale",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "startedAt",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "expiredAt",
        type: "uint256",
      },
    ],
    name: "PresaleCreated",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122016944f14c4e61e4987da564a7e08b01560b336e4ed554a51e529d4ea01e52d6e64736f6c63430008040033";

export class LaunchPadLib__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LaunchPadLib> {
    return super.deploy(overrides || {}) as Promise<LaunchPadLib>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LaunchPadLib {
    return super.attach(address) as LaunchPadLib;
  }
  connect(signer: Signer): LaunchPadLib__factory {
    return super.connect(signer) as LaunchPadLib__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LaunchPadLibInterface {
    return new utils.Interface(_abi) as LaunchPadLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LaunchPadLib {
    return new Contract(address, _abi, signerOrProvider) as LaunchPadLib;
  }
}
