/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { LPLocker, LPLockerInterface } from "../LPLocker";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_lockerID",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_numOfTokens",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_unlockTime",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "unlockTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161039038038061039083398101604081905261002f91610147565b6040518060e00160405280868152602001856001600160a01b03168152602001846001600160a01b031681526020018381526020014281526020018281526020016000600181111561009157634e487b7160e01b600052602160045260246000fd5b9052805160009081556020820151600180546001600160a01b039283166001600160a01b0319918216178255604085015160028054919094169116179091556060830151600355608083015160045560a083015160055560c0830151600680549192909160ff191690838181111561011957634e487b7160e01b600052602160045260246000fd5b02179055509050505050505050610195565b80516001600160a01b038116811461014257600080fd5b919050565b600080600080600060a0868803121561015e578081fd5b8551945061016e6020870161012b565b935061017c6040870161012b565b6060870151608090970151959894975095949392505050565b6101ec806101a46000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063f968f49314610030575b600080fd5b61003861003a565b005b6001546001600160a01b031633146100995760405162461bcd60e51b815260206004820152601d60248201527f4f6e6c79206c6f636b6572206f6e77657220697320616c6c6f7765642e00000060448201526064015b60405180910390fd5b6001546001600160a01b031633146100f35760405162461bcd60e51b815260206004820152601d60248201527f4f6e6c79206c6f636b6572206f6e77657220697320616c6c6f7765642e0000006044820152606401610090565b60025460015460035460405163a9059cbb60e01b81526001600160a01b039283166004820152602481019190915291169063a9059cbb90604401602060405180830381600087803b15801561014757600080fd5b505af115801561015b573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061017f919061018f565b506006805460ff19166001179055565b6000602082840312156101a0578081fd5b815180151581146101af578182fd5b939250505056fea264697066735822122098dea92bca2f3d7138dbfe9a26ec1be787de718e3ca84ff927c07295417cb1af64736f6c63430008040033";

export class LPLocker__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    _lockerID: BigNumberish,
    _owner: string,
    _token: string,
    _numOfTokens: BigNumberish,
    _unlockTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LPLocker> {
    return super.deploy(
      _lockerID,
      _owner,
      _token,
      _numOfTokens,
      _unlockTime,
      overrides || {}
    ) as Promise<LPLocker>;
  }
  getDeployTransaction(
    _lockerID: BigNumberish,
    _owner: string,
    _token: string,
    _numOfTokens: BigNumberish,
    _unlockTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _lockerID,
      _owner,
      _token,
      _numOfTokens,
      _unlockTime,
      overrides || {}
    );
  }
  attach(address: string): LPLocker {
    return super.attach(address) as LPLocker;
  }
  connect(signer: Signer): LPLocker__factory {
    return super.connect(signer) as LPLocker__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LPLockerInterface {
    return new utils.Interface(_abi) as LPLockerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LPLocker {
    return new Contract(address, _abi, signerOrProvider) as LPLocker;
  }
}
