/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { SalesTracker, SalesTrackerInterface } from "../SalesTracker";

const _abi = [
  {
    inputs: [],
    name: "activeSalesCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "activeSalesList",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "containsActiveSale",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class SalesTracker__factory {
  static readonly abi = _abi;
  static createInterface(): SalesTrackerInterface {
    return new utils.Interface(_abi) as SalesTrackerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SalesTracker {
    return new Contract(address, _abi, signerOrProvider) as SalesTracker;
  }
}
