/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "AccessControlEnumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControlEnumerable__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "IAccessControlEnumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControlEnumerable__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Burnable__factory>;
    getContractFactory(
      name: "ERC20Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Pausable__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC20PresetMinterPauser",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20PresetMinterPauser__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IUniswapV2Callee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Callee__factory>;
    getContractFactory(
      name: "IUniswapV2ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2ERC20__factory>;
    getContractFactory(
      name: "IUniswapV2Factory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Factory__factory>;
    getContractFactory(
      name: "IUniswapV2Pair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Pair__factory>;
    getContractFactory(
      name: "UniswapV2ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapV2ERC20__factory>;
    getContractFactory(
      name: "UniswapV2Factory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapV2Factory__factory>;
    getContractFactory(
      name: "UniswapV2Pair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapV2Pair__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IUniswapV2Router01",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Router01__factory>;
    getContractFactory(
      name: "IUniswapV2Router02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Router02__factory>;
    getContractFactory(
      name: "IWETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWETH__factory>;
    getContractFactory(
      name: "UniswapV2Router02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapV2Router02__factory>;
    getContractFactory(
      name: "BEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BEP20__factory>;
    getContractFactory(
      name: "PICNICToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PICNICToken__factory>;
    getContractFactory(
      name: "PresaleToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PresaleToken__factory>;
    getContractFactory(
      name: "TestCoin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestCoin__factory>;
    getContractFactory(
      name: "UniswapV2FactoryClone",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapV2FactoryClone__factory>;
    getContractFactory(
      name: "UniswapV2PairClone",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapV2PairClone__factory>;
    getContractFactory(
      name: "UniswapV2Router02Clone",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapV2Router02Clone__factory>;
    getContractFactory(
      name: "WETH9",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WETH9__factory>;
    getContractFactory(
      name: "ILPLokcerManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILPLokcerManager__factory>;
    getContractFactory(
      name: "Launchpadv2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Launchpadv2__factory>;
    getContractFactory(
      name: "Presale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Presale__factory>;
    getContractFactory(
      name: "ILockerFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILockerFactory__factory>;
    getContractFactory(
      name: "ILockerFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILockerFactory__factory>;
    getContractFactory(
      name: "Launchpad",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Launchpad__factory>;
    getContractFactory(
      name: "SalesTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SalesTracker__factory>;
    getContractFactory(
      name: "IPLock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPLock__factory>;
    getContractFactory(
      name: "Locker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Locker__factory>;
    getContractFactory(
      name: "LokcerFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LokcerFactory__factory>;
    getContractFactory(
      name: "PICNICLocker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PICNICLocker__factory>;
    getContractFactory(
      name: "LPLocker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LPLocker__factory>;
    getContractFactory(
      name: "LPLokcerManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LPLokcerManager__factory>;

    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "AccessControlEnumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControlEnumerable>;
    getContractAt(
      name: "IAccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "IAccessControlEnumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControlEnumerable>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Burnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Burnable>;
    getContractAt(
      name: "ERC20Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Pausable>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC20PresetMinterPauser",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20PresetMinterPauser>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IUniswapV2Callee",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Callee>;
    getContractAt(
      name: "IUniswapV2ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2ERC20>;
    getContractAt(
      name: "IUniswapV2Factory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Factory>;
    getContractAt(
      name: "IUniswapV2Pair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Pair>;
    getContractAt(
      name: "UniswapV2ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapV2ERC20>;
    getContractAt(
      name: "UniswapV2Factory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapV2Factory>;
    getContractAt(
      name: "UniswapV2Pair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapV2Pair>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IUniswapV2Router01",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Router01>;
    getContractAt(
      name: "IUniswapV2Router02",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Router02>;
    getContractAt(
      name: "IWETH",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWETH>;
    getContractAt(
      name: "UniswapV2Router02",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapV2Router02>;
    getContractAt(
      name: "BEP20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BEP20>;
    getContractAt(
      name: "PICNICToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PICNICToken>;
    getContractAt(
      name: "PresaleToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PresaleToken>;
    getContractAt(
      name: "TestCoin",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestCoin>;
    getContractAt(
      name: "UniswapV2FactoryClone",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapV2FactoryClone>;
    getContractAt(
      name: "UniswapV2PairClone",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapV2PairClone>;
    getContractAt(
      name: "UniswapV2Router02Clone",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapV2Router02Clone>;
    getContractAt(
      name: "WETH9",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WETH9>;
    getContractAt(
      name: "ILPLokcerManager",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILPLokcerManager>;
    getContractAt(
      name: "Launchpadv2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Launchpadv2>;
    getContractAt(
      name: "Presale",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Presale>;
    getContractAt(
      name: "ILockerFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILockerFactory>;
    getContractAt(
      name: "ILockerFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILockerFactory>;
    getContractAt(
      name: "Launchpad",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Launchpad>;
    getContractAt(
      name: "SalesTracker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SalesTracker>;
    getContractAt(
      name: "IPLock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPLock>;
    getContractAt(
      name: "Locker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Locker>;
    getContractAt(
      name: "LokcerFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LokcerFactory>;
    getContractAt(
      name: "PICNICLocker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PICNICLocker>;
    getContractAt(
      name: "LPLocker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LPLocker>;
    getContractAt(
      name: "LPLokcerManager",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LPLokcerManager>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
