/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LaunchPadLibInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "PresaleCreated(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PresaleCreated"): EventFragment;
}

export type PresaleCreatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber] & {
    owner: string;
    tokensForSale: BigNumber;
    startedAt: BigNumber;
    expiredAt: BigNumber;
  }
>;

export class LaunchPadLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LaunchPadLibInterface;

  functions: {};

  callStatic: {};

  filters: {
    "PresaleCreated(address,uint256,uint256,uint256)"(
      owner?: null,
      tokensForSale?: null,
      startedAt?: null,
      expiredAt?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        owner: string;
        tokensForSale: BigNumber;
        startedAt: BigNumber;
        expiredAt: BigNumber;
      }
    >;

    PresaleCreated(
      owner?: null,
      tokensForSale?: null,
      startedAt?: null,
      expiredAt?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        owner: string;
        tokensForSale: BigNumber;
        startedAt: BigNumber;
        expiredAt: BigNumber;
      }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
