/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LPLokcerManagerInterface extends ethers.utils.Interface {
  functions: {
    "createLPLcoker(address,address,uint256,uint256)": FunctionFragment;
    "getLockersListbyToken(address)": FunctionFragment;
    "getLockersListbyUser(address)": FunctionFragment;
    "launchpadAddress()": FunctionFragment;
    "lockerCount()": FunctionFragment;
    "lockerInfo(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createLPLcoker",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockersListbyToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockersListbyUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "launchpadAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockerInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createLPLcoker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockersListbyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockersListbyUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "launchpadAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockerInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "LPLocked(uint256,address,address,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LPLocked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type LPLockedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber] & {
    id: BigNumber;
    owner: string;
    token: string;
    numOfTokens: BigNumber;
    unlockTime: BigNumber;
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class LPLokcerManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LPLokcerManagerInterface;

  functions: {
    createLPLcoker(
      _owner: string,
      _token: string,
      _numOfTokens: BigNumberish,
      _unlockTime: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getLockersListbyToken(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getLockersListbyUser(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    launchpadAddress(overrides?: CallOverrides): Promise<[string]>;

    lockerCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    lockerInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, BigNumber, BigNumber] & {
        id: BigNumber;
        owner: string;
        token: string;
        numOfTokens: BigNumber;
        lockTime: BigNumber;
        unlockTime: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createLPLcoker(
    _owner: string,
    _token: string,
    _numOfTokens: BigNumberish,
    _unlockTime: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getLockersListbyToken(
    _tokenAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getLockersListbyUser(
    _userAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  launchpadAddress(overrides?: CallOverrides): Promise<string>;

  lockerCount(overrides?: CallOverrides): Promise<BigNumber>;

  lockerInfo(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, BigNumber, BigNumber] & {
      id: BigNumber;
      owner: string;
      token: string;
      numOfTokens: BigNumber;
      lockTime: BigNumber;
      unlockTime: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createLPLcoker(
      _owner: string,
      _token: string,
      _numOfTokens: BigNumberish,
      _unlockTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLockersListbyToken(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getLockersListbyUser(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    launchpadAddress(overrides?: CallOverrides): Promise<string>;

    lockerCount(overrides?: CallOverrides): Promise<BigNumber>;

    lockerInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, BigNumber, BigNumber] & {
        id: BigNumber;
        owner: string;
        token: string;
        numOfTokens: BigNumber;
        lockTime: BigNumber;
        unlockTime: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "LPLocked(uint256,address,address,uint256,uint256)"(
      id?: null,
      owner?: null,
      token?: null,
      numOfTokens?: null,
      unlockTime?: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, BigNumber],
      {
        id: BigNumber;
        owner: string;
        token: string;
        numOfTokens: BigNumber;
        unlockTime: BigNumber;
      }
    >;

    LPLocked(
      id?: null,
      owner?: null,
      token?: null,
      numOfTokens?: null,
      unlockTime?: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, BigNumber],
      {
        id: BigNumber;
        owner: string;
        token: string;
        numOfTokens: BigNumber;
        unlockTime: BigNumber;
      }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    createLPLcoker(
      _owner: string,
      _token: string,
      _numOfTokens: BigNumberish,
      _unlockTime: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getLockersListbyToken(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLockersListbyUser(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    launchpadAddress(overrides?: CallOverrides): Promise<BigNumber>;

    lockerCount(overrides?: CallOverrides): Promise<BigNumber>;

    lockerInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createLPLcoker(
      _owner: string,
      _token: string,
      _numOfTokens: BigNumberish,
      _unlockTime: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getLockersListbyToken(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLockersListbyUser(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    launchpadAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockerCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockerInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
