/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PresaleInterface extends ethers.utils.Interface {
  functions: {
    "cancelSale()": FunctionFragment;
    "chageSaleType(uint8,address,uint256)": FunctionFragment;
    "claimTokensOrARefund()": FunctionFragment;
    "contributeToSale()": FunctionFragment;
    "contributorCycles()": FunctionFragment;
    "contributorVestingRecord(uint256)": FunctionFragment;
    "contributorsVesting()": FunctionFragment;
    "emergencyWithdraw()": FunctionFragment;
    "finalizePresale()": FunctionFragment;
    "finalizingTime()": FunctionFragment;
    "generalInfo()": FunctionFragment;
    "getContributorReleaseStatus(uint256,address)": FunctionFragment;
    "getWhiteListUsers()": FunctionFragment;
    "isWhiteListed(address)": FunctionFragment;
    "master()": FunctionFragment;
    "participant(address)": FunctionFragment;
    "participationCriteria()": FunctionFragment;
    "presaleCounts()": FunctionFragment;
    "presaleInfo()": FunctionFragment;
    "presaleTimes()": FunctionFragment;
    "removeWhiteListUsers(address[])": FunctionFragment;
    "salesFeeInPercent()": FunctionFragment;
    "teamVesting()": FunctionFragment;
    "teamVestingRecord(uint256)": FunctionFragment;
    "temaVestingCycles()": FunctionFragment;
    "tokenInfo()": FunctionFragment;
    "uniswapV2Router02()": FunctionFragment;
    "unlockLPTokens()": FunctionFragment;
    "unlockTokens()": FunctionFragment;
    "updateGeneralInfo((string,string,string,string,string,string))": FunctionFragment;
    "whiteListUsers(address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cancelSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chageSaleType",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokensOrARefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributeToSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributorCycles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributorVestingRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorsVesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizePresale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizingTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generalInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorReleaseStatus",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhiteListUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isWhiteListed",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "master", values?: undefined): string;
  encodeFunctionData(functionFragment: "participant", values: [string]): string;
  encodeFunctionData(
    functionFragment: "participationCriteria",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleCounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleTimes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeWhiteListUsers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "salesFeeInPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamVesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamVestingRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "temaVestingCycles",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tokenInfo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Router02",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockLPTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateGeneralInfo",
    values: [
      {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "whiteListUsers",
    values: [string[]]
  ): string;

  decodeFunctionResult(functionFragment: "cancelSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chageSaleType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokensOrARefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributeToSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorVestingRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorsVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizePresale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizingTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generalInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorReleaseStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhiteListUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhiteListed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "master", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participationCriteria",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWhiteListUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salesFeeInPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teamVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teamVestingRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "temaVestingCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Router02",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockLPTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGeneralInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whiteListUsers",
    data: BytesLike
  ): Result;

  events: {
    "Claimed(address,uint256,uint256)": EventFragment;
    "ContributionsAdded(address,uint256,uint256)": EventFragment;
    "ContributionsRemoved(address,uint256)": EventFragment;
    "Finalized(uint8,uint256)": EventFragment;
    "SaleTypeChanged(uint8,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Claimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionsAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionsRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Finalized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaleTypeChanged"): EventFragment;
}

export type ClaimedEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    contributor: string;
    value: BigNumber;
    tokens: BigNumber;
  }
>;

export type ContributionsAddedEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    contributor: string;
    amount: BigNumber;
    requestedTokens: BigNumber;
  }
>;

export type ContributionsRemovedEvent = TypedEvent<
  [string, BigNumber] & { contributor: string; amount: BigNumber }
>;

export type FinalizedEvent = TypedEvent<
  [number, BigNumber] & { status: number; finalizedTime: BigNumber }
>;

export type SaleTypeChangedEvent = TypedEvent<
  [number, string, BigNumber] & {
    _type: number;
    _address: string;
    minimumTokens: BigNumber;
  }
>;

export class Presale extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PresaleInterface;

  functions: {
    cancelSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    chageSaleType(
      _type: BigNumberish,
      _address: string,
      minimumTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimTokensOrARefund(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    contributeToSale(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    contributorCycles(overrides?: CallOverrides): Promise<[BigNumber]>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
      }
    >;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, number] & {
        isEnabled: boolean;
        firstReleasePC: BigNumber;
        eachCycleDuration: BigNumber;
        eachCyclePC: number;
      }
    >;

    emergencyWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finalizePresale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finalizingTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    generalInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, string] & {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      }
    >;

    getContributorReleaseStatus(
      _time: BigNumberish,
      _address: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getWhiteListUsers(overrides?: CallOverrides): Promise<[string[]]>;

    isWhiteListed(user: string, overrides?: CallOverrides): Promise<[boolean]>;

    master(overrides?: CallOverrides): Promise<[string]>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }
    >;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        string,
        BigNumber,
        BigNumber,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        presaleType: number;
        criteriaToken: string;
        minCriteriaTokens: BigNumber;
        presaleRate: BigNumber;
        liquidity: number;
        hardCap: BigNumber;
        softCap: BigNumber;
        minContribution: BigNumber;
        maxContribution: BigNumber;
        refundType: number;
      }
    >;

    presaleCounts(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        accumulatedBalance: BigNumber;
        contributors: BigNumber;
        claimsCount: BigNumber;
      }
    >;

    presaleInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, number] & {
        id: BigNumber;
        presaleOwner: string;
        preSaleStatus: number;
      }
    >;

    presaleTimes(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        startedAt: BigNumber;
        expiredAt: BigNumber;
        lpLockupDuration: BigNumber;
      }
    >;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    salesFeeInPercent(overrides?: CallOverrides): Promise<[number]>;

    teamVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        isEnabled: boolean;
        vestingTokens: BigNumber;
        firstReleaseDelay: BigNumber;
        firstReleasePC: BigNumber;
        eachCycleDuration: BigNumber;
        eachCyclePC: number;
      }
    >;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
        releaseStatus: number;
      }
    >;

    temaVestingCycles(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokenInfo(
      overrides?: CallOverrides
    ): Promise<[string, number] & { tokenAddress: string; decimals: number }>;

    uniswapV2Router02(overrides?: CallOverrides): Promise<[string]>;

    unlockLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlockTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateGeneralInfo(
      _generalInfo: {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  cancelSale(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  chageSaleType(
    _type: BigNumberish,
    _address: string,
    minimumTokens: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimTokensOrARefund(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  contributeToSale(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

  contributorVestingRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      cycle: BigNumber;
      releaseTime: BigNumber;
      tokensPC: BigNumber;
      percentageToRelease: BigNumber;
    }
  >;

  contributorsVesting(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, number] & {
      isEnabled: boolean;
      firstReleasePC: BigNumber;
      eachCycleDuration: BigNumber;
      eachCyclePC: number;
    }
  >;

  emergencyWithdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finalizePresale(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finalizingTime(overrides?: CallOverrides): Promise<BigNumber>;

  generalInfo(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string, string] & {
      logoURL: string;
      websiteURL: string;
      twitterURL: string;
      telegramURL: string;
      discordURL: string;
      description: string;
    }
  >;

  getContributorReleaseStatus(
    _time: BigNumberish,
    _address: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getWhiteListUsers(overrides?: CallOverrides): Promise<string[]>;

  isWhiteListed(user: string, overrides?: CallOverrides): Promise<boolean>;

  master(overrides?: CallOverrides): Promise<string>;

  participant(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }>;

  participationCriteria(
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      string,
      BigNumber,
      BigNumber,
      number,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      number
    ] & {
      presaleType: number;
      criteriaToken: string;
      minCriteriaTokens: BigNumber;
      presaleRate: BigNumber;
      liquidity: number;
      hardCap: BigNumber;
      softCap: BigNumber;
      minContribution: BigNumber;
      maxContribution: BigNumber;
      refundType: number;
    }
  >;

  presaleCounts(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      accumulatedBalance: BigNumber;
      contributors: BigNumber;
      claimsCount: BigNumber;
    }
  >;

  presaleInfo(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, number] & {
      id: BigNumber;
      presaleOwner: string;
      preSaleStatus: number;
    }
  >;

  presaleTimes(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      startedAt: BigNumber;
      expiredAt: BigNumber;
      lpLockupDuration: BigNumber;
    }
  >;

  removeWhiteListUsers(
    _addresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  salesFeeInPercent(overrides?: CallOverrides): Promise<number>;

  teamVesting(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      isEnabled: boolean;
      vestingTokens: BigNumber;
      firstReleaseDelay: BigNumber;
      firstReleasePC: BigNumber;
      eachCycleDuration: BigNumber;
      eachCyclePC: number;
    }
  >;

  teamVestingRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      cycle: BigNumber;
      releaseTime: BigNumber;
      tokensPC: BigNumber;
      percentageToRelease: BigNumber;
      releaseStatus: number;
    }
  >;

  temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

  tokenInfo(
    overrides?: CallOverrides
  ): Promise<[string, number] & { tokenAddress: string; decimals: number }>;

  uniswapV2Router02(overrides?: CallOverrides): Promise<string>;

  unlockLPTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlockTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateGeneralInfo(
    _generalInfo: {
      logoURL: string;
      websiteURL: string;
      twitterURL: string;
      telegramURL: string;
      discordURL: string;
      description: string;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  whiteListUsers(
    _addresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cancelSale(overrides?: CallOverrides): Promise<void>;

    chageSaleType(
      _type: BigNumberish,
      _address: string,
      minimumTokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTokensOrARefund(overrides?: CallOverrides): Promise<void>;

    contributeToSale(overrides?: CallOverrides): Promise<void>;

    contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
      }
    >;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, number] & {
        isEnabled: boolean;
        firstReleasePC: BigNumber;
        eachCycleDuration: BigNumber;
        eachCyclePC: number;
      }
    >;

    emergencyWithdraw(overrides?: CallOverrides): Promise<void>;

    finalizePresale(overrides?: CallOverrides): Promise<void>;

    finalizingTime(overrides?: CallOverrides): Promise<BigNumber>;

    generalInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, string] & {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      }
    >;

    getContributorReleaseStatus(
      _time: BigNumberish,
      _address: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getWhiteListUsers(overrides?: CallOverrides): Promise<string[]>;

    isWhiteListed(user: string, overrides?: CallOverrides): Promise<boolean>;

    master(overrides?: CallOverrides): Promise<string>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }
    >;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        string,
        BigNumber,
        BigNumber,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        presaleType: number;
        criteriaToken: string;
        minCriteriaTokens: BigNumber;
        presaleRate: BigNumber;
        liquidity: number;
        hardCap: BigNumber;
        softCap: BigNumber;
        minContribution: BigNumber;
        maxContribution: BigNumber;
        refundType: number;
      }
    >;

    presaleCounts(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        accumulatedBalance: BigNumber;
        contributors: BigNumber;
        claimsCount: BigNumber;
      }
    >;

    presaleInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, number] & {
        id: BigNumber;
        presaleOwner: string;
        preSaleStatus: number;
      }
    >;

    presaleTimes(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        startedAt: BigNumber;
        expiredAt: BigNumber;
        lpLockupDuration: BigNumber;
      }
    >;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    salesFeeInPercent(overrides?: CallOverrides): Promise<number>;

    teamVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        isEnabled: boolean;
        vestingTokens: BigNumber;
        firstReleaseDelay: BigNumber;
        firstReleasePC: BigNumber;
        eachCycleDuration: BigNumber;
        eachCyclePC: number;
      }
    >;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
        releaseStatus: number;
      }
    >;

    temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

    tokenInfo(
      overrides?: CallOverrides
    ): Promise<[string, number] & { tokenAddress: string; decimals: number }>;

    uniswapV2Router02(overrides?: CallOverrides): Promise<string>;

    unlockLPTokens(overrides?: CallOverrides): Promise<void>;

    unlockTokens(overrides?: CallOverrides): Promise<void>;

    updateGeneralInfo(
      _generalInfo: {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    whiteListUsers(
      _addresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Claimed(address,uint256,uint256)"(
      contributor?: null,
      value?: null,
      tokens?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { contributor: string; value: BigNumber; tokens: BigNumber }
    >;

    Claimed(
      contributor?: null,
      value?: null,
      tokens?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { contributor: string; value: BigNumber; tokens: BigNumber }
    >;

    "ContributionsAdded(address,uint256,uint256)"(
      contributor?: null,
      amount?: null,
      requestedTokens?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { contributor: string; amount: BigNumber; requestedTokens: BigNumber }
    >;

    ContributionsAdded(
      contributor?: null,
      amount?: null,
      requestedTokens?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { contributor: string; amount: BigNumber; requestedTokens: BigNumber }
    >;

    "ContributionsRemoved(address,uint256)"(
      contributor?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { contributor: string; amount: BigNumber }
    >;

    ContributionsRemoved(
      contributor?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { contributor: string; amount: BigNumber }
    >;

    "Finalized(uint8,uint256)"(
      status?: null,
      finalizedTime?: null
    ): TypedEventFilter<
      [number, BigNumber],
      { status: number; finalizedTime: BigNumber }
    >;

    Finalized(
      status?: null,
      finalizedTime?: null
    ): TypedEventFilter<
      [number, BigNumber],
      { status: number; finalizedTime: BigNumber }
    >;

    "SaleTypeChanged(uint8,address,uint256)"(
      _type?: null,
      _address?: null,
      minimumTokens?: null
    ): TypedEventFilter<
      [number, string, BigNumber],
      { _type: number; _address: string; minimumTokens: BigNumber }
    >;

    SaleTypeChanged(
      _type?: null,
      _address?: null,
      minimumTokens?: null
    ): TypedEventFilter<
      [number, string, BigNumber],
      { _type: number; _address: string; minimumTokens: BigNumber }
    >;
  };

  estimateGas: {
    cancelSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    chageSaleType(
      _type: BigNumberish,
      _address: string,
      minimumTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimTokensOrARefund(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    contributeToSale(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contributorsVesting(overrides?: CallOverrides): Promise<BigNumber>;

    emergencyWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finalizePresale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finalizingTime(overrides?: CallOverrides): Promise<BigNumber>;

    generalInfo(overrides?: CallOverrides): Promise<BigNumber>;

    getContributorReleaseStatus(
      _time: BigNumberish,
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWhiteListUsers(overrides?: CallOverrides): Promise<BigNumber>;

    isWhiteListed(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    master(overrides?: CallOverrides): Promise<BigNumber>;

    participant(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    participationCriteria(overrides?: CallOverrides): Promise<BigNumber>;

    presaleCounts(overrides?: CallOverrides): Promise<BigNumber>;

    presaleInfo(overrides?: CallOverrides): Promise<BigNumber>;

    presaleTimes(overrides?: CallOverrides): Promise<BigNumber>;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    salesFeeInPercent(overrides?: CallOverrides): Promise<BigNumber>;

    teamVesting(overrides?: CallOverrides): Promise<BigNumber>;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

    tokenInfo(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV2Router02(overrides?: CallOverrides): Promise<BigNumber>;

    unlockLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlockTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateGeneralInfo(
      _generalInfo: {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    chageSaleType(
      _type: BigNumberish,
      _address: string,
      minimumTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimTokensOrARefund(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    contributeToSale(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    contributorCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    emergencyWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finalizePresale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finalizingTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    generalInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getContributorReleaseStatus(
      _time: BigNumberish,
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWhiteListUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isWhiteListed(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    master(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presaleCounts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    presaleInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    presaleTimes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    salesFeeInPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    teamVesting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    temaVestingCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uniswapV2Router02(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unlockLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlockTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateGeneralInfo(
      _generalInfo: {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
