/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PresaleInterface extends ethers.utils.Interface {
  functions: {
    "buyTokensOnPresale(uint256)": FunctionFragment;
    "contributorCycles()": FunctionFragment;
    "contributorVestingRecord(uint256)": FunctionFragment;
    "contributorsVesting()": FunctionFragment;
    "extraTokens()": FunctionFragment;
    "finalizingTime()": FunctionFragment;
    "generalInfo()": FunctionFragment;
    "master()": FunctionFragment;
    "participant(address)": FunctionFragment;
    "participationCriteria()": FunctionFragment;
    "presaleCounts()": FunctionFragment;
    "presaleInfo()": FunctionFragment;
    "presaleTimes()": FunctionFragment;
    "salesFeeInPercent()": FunctionFragment;
    "teamVesting()": FunctionFragment;
    "teamVestingRecord(uint256)": FunctionFragment;
    "temaVestingCycles()": FunctionFragment;
    "tokenInfo()": FunctionFragment;
    "uniswapV2Router02()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyTokensOnPresale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorCycles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributorVestingRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorsVesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "extraTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizingTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generalInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "master", values?: undefined): string;
  encodeFunctionData(functionFragment: "participant", values: [string]): string;
  encodeFunctionData(
    functionFragment: "participationCriteria",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleCounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleTimes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "salesFeeInPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamVesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamVestingRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "temaVestingCycles",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tokenInfo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Router02",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "buyTokensOnPresale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorVestingRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorsVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extraTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizingTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generalInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "master", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participationCriteria",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salesFeeInPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teamVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teamVestingRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "temaVestingCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Router02",
    data: BytesLike
  ): Result;

  events: {};
}

export class Presale extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PresaleInterface;

  functions: {
    buyTokensOnPresale(
      numOfTokensRequested: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    contributorCycles(overrides?: CallOverrides): Promise<[BigNumber]>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
      }
    >;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, number] & {
        isEnabled: boolean;
        firstReleasePC: BigNumber;
        eachCycleDuration: BigNumber;
        eachCyclePC: number;
      }
    >;

    extraTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    finalizingTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    generalInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, string] & {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      }
    >;

    master(overrides?: CallOverrides): Promise<[string]>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }
    >;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        string,
        BigNumber,
        BigNumber,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        saleType: number;
        criteriaTokenAddress: string;
        minCriteriaTokens: BigNumber;
        presaleRate: BigNumber;
        liquidity: number;
        hardCap: BigNumber;
        softCap: BigNumber;
        minBuy: BigNumber;
        maxBuy: BigNumber;
        refundType: number;
      }
    >;

    presaleCounts(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        accumulatedBalance: BigNumber;
        contributors: BigNumber;
        claimsCount: BigNumber;
      }
    >;

    presaleInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, number] & {
        id: BigNumber;
        presaleOwner: string;
        preSaleStatus: number;
      }
    >;

    presaleTimes(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        startedAt: BigNumber;
        expiredAt: BigNumber;
        lpLockupDuration: BigNumber;
      }
    >;

    salesFeeInPercent(overrides?: CallOverrides): Promise<[number]>;

    teamVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        isEnabled: boolean;
        vestingTokens: BigNumber;
        firstReleaseTime: BigNumber;
        firstReleasePC: BigNumber;
        eachCycleDuration: BigNumber;
        eachCyclePC: number;
      }
    >;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
        releaseStatus: number;
      }
    >;

    temaVestingCycles(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokenInfo(
      overrides?: CallOverrides
    ): Promise<[string, number] & { tokenAddress: string; decimals: number }>;

    uniswapV2Router02(overrides?: CallOverrides): Promise<[string]>;
  };

  buyTokensOnPresale(
    numOfTokensRequested: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

  contributorVestingRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      cycle: BigNumber;
      releaseTime: BigNumber;
      tokensPC: BigNumber;
      percentageToRelease: BigNumber;
    }
  >;

  contributorsVesting(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, number] & {
      isEnabled: boolean;
      firstReleasePC: BigNumber;
      eachCycleDuration: BigNumber;
      eachCyclePC: number;
    }
  >;

  extraTokens(overrides?: CallOverrides): Promise<BigNumber>;

  finalizingTime(overrides?: CallOverrides): Promise<BigNumber>;

  generalInfo(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string, string] & {
      logoURL: string;
      websiteURL: string;
      twitterURL: string;
      telegramURL: string;
      discordURL: string;
      description: string;
    }
  >;

  master(overrides?: CallOverrides): Promise<string>;

  participant(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }>;

  participationCriteria(
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      string,
      BigNumber,
      BigNumber,
      number,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      number
    ] & {
      saleType: number;
      criteriaTokenAddress: string;
      minCriteriaTokens: BigNumber;
      presaleRate: BigNumber;
      liquidity: number;
      hardCap: BigNumber;
      softCap: BigNumber;
      minBuy: BigNumber;
      maxBuy: BigNumber;
      refundType: number;
    }
  >;

  presaleCounts(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      accumulatedBalance: BigNumber;
      contributors: BigNumber;
      claimsCount: BigNumber;
    }
  >;

  presaleInfo(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, number] & {
      id: BigNumber;
      presaleOwner: string;
      preSaleStatus: number;
    }
  >;

  presaleTimes(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      startedAt: BigNumber;
      expiredAt: BigNumber;
      lpLockupDuration: BigNumber;
    }
  >;

  salesFeeInPercent(overrides?: CallOverrides): Promise<number>;

  teamVesting(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      isEnabled: boolean;
      vestingTokens: BigNumber;
      firstReleaseTime: BigNumber;
      firstReleasePC: BigNumber;
      eachCycleDuration: BigNumber;
      eachCyclePC: number;
    }
  >;

  teamVestingRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      cycle: BigNumber;
      releaseTime: BigNumber;
      tokensPC: BigNumber;
      percentageToRelease: BigNumber;
      releaseStatus: number;
    }
  >;

  temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

  tokenInfo(
    overrides?: CallOverrides
  ): Promise<[string, number] & { tokenAddress: string; decimals: number }>;

  uniswapV2Router02(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    buyTokensOnPresale(
      numOfTokensRequested: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
      }
    >;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, number] & {
        isEnabled: boolean;
        firstReleasePC: BigNumber;
        eachCycleDuration: BigNumber;
        eachCyclePC: number;
      }
    >;

    extraTokens(overrides?: CallOverrides): Promise<BigNumber>;

    finalizingTime(overrides?: CallOverrides): Promise<BigNumber>;

    generalInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, string] & {
        logoURL: string;
        websiteURL: string;
        twitterURL: string;
        telegramURL: string;
        discordURL: string;
        description: string;
      }
    >;

    master(overrides?: CallOverrides): Promise<string>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }
    >;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        string,
        BigNumber,
        BigNumber,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        saleType: number;
        criteriaTokenAddress: string;
        minCriteriaTokens: BigNumber;
        presaleRate: BigNumber;
        liquidity: number;
        hardCap: BigNumber;
        softCap: BigNumber;
        minBuy: BigNumber;
        maxBuy: BigNumber;
        refundType: number;
      }
    >;

    presaleCounts(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        accumulatedBalance: BigNumber;
        contributors: BigNumber;
        claimsCount: BigNumber;
      }
    >;

    presaleInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, number] & {
        id: BigNumber;
        presaleOwner: string;
        preSaleStatus: number;
      }
    >;

    presaleTimes(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        startedAt: BigNumber;
        expiredAt: BigNumber;
        lpLockupDuration: BigNumber;
      }
    >;

    salesFeeInPercent(overrides?: CallOverrides): Promise<number>;

    teamVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        isEnabled: boolean;
        vestingTokens: BigNumber;
        firstReleaseTime: BigNumber;
        firstReleasePC: BigNumber;
        eachCycleDuration: BigNumber;
        eachCyclePC: number;
      }
    >;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
        releaseStatus: number;
      }
    >;

    temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

    tokenInfo(
      overrides?: CallOverrides
    ): Promise<[string, number] & { tokenAddress: string; decimals: number }>;

    uniswapV2Router02(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    buyTokensOnPresale(
      numOfTokensRequested: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contributorsVesting(overrides?: CallOverrides): Promise<BigNumber>;

    extraTokens(overrides?: CallOverrides): Promise<BigNumber>;

    finalizingTime(overrides?: CallOverrides): Promise<BigNumber>;

    generalInfo(overrides?: CallOverrides): Promise<BigNumber>;

    master(overrides?: CallOverrides): Promise<BigNumber>;

    participant(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    participationCriteria(overrides?: CallOverrides): Promise<BigNumber>;

    presaleCounts(overrides?: CallOverrides): Promise<BigNumber>;

    presaleInfo(overrides?: CallOverrides): Promise<BigNumber>;

    presaleTimes(overrides?: CallOverrides): Promise<BigNumber>;

    salesFeeInPercent(overrides?: CallOverrides): Promise<BigNumber>;

    teamVesting(overrides?: CallOverrides): Promise<BigNumber>;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

    tokenInfo(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV2Router02(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTokensOnPresale(
      numOfTokensRequested: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    contributorCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    extraTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    finalizingTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    generalInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    master(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presaleCounts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    presaleInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    presaleTimes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    salesFeeInPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    teamVesting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    temaVestingCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uniswapV2Router02(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
