/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PresaleInterface extends ethers.utils.Interface {
  functions: {
    "buyTokensOnPresale(uint256)": FunctionFragment;
    "chageSaleType(uint8,address,uint256)": FunctionFragment;
    "claimTokensOrARefund()": FunctionFragment;
    "contributorCycles()": FunctionFragment;
    "contributorVestingRecord(uint256)": FunctionFragment;
    "contributorsVesting()": FunctionFragment;
    "emergencyWithdraw()": FunctionFragment;
    "finalizePresale()": FunctionFragment;
    "getContributorsList()": FunctionFragment;
    "getWhiteListUsers()": FunctionFragment;
    "internalData()": FunctionFragment;
    "isWhiteListed(address)": FunctionFragment;
    "launchpadAddresses()": FunctionFragment;
    "master()": FunctionFragment;
    "owner()": FunctionFragment;
    "participant(address)": FunctionFragment;
    "participationCriteria()": FunctionFragment;
    "presaleCounts()": FunctionFragment;
    "presaleInfo()": FunctionFragment;
    "presaleTimes()": FunctionFragment;
    "removeWhiteListUsers(address[])": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reqestedTokens()": FunctionFragment;
    "salesFeeInPercent()": FunctionFragment;
    "teamVesting()": FunctionFragment;
    "teamVestingRecord(uint256)": FunctionFragment;
    "temaVestingCycles()": FunctionFragment;
    "tokenInfo()": FunctionFragment;
    "tokenomics()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unlockLPTokens()": FunctionFragment;
    "unlockTokens()": FunctionFragment;
    "whiteListUsers(address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyTokensOnPresale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chageSaleType",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokensOrARefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributorCycles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributorVestingRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorsVesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizePresale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorsList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWhiteListUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "internalData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isWhiteListed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "launchpadAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "master", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "participant", values: [string]): string;
  encodeFunctionData(
    functionFragment: "participationCriteria",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleCounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleTimes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeWhiteListUsers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reqestedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "salesFeeInPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamVesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamVestingRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "temaVestingCycles",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tokenInfo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenomics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockLPTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whiteListUsers",
    values: [string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyTokensOnPresale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chageSaleType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokensOrARefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorVestingRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorsVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizePresale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorsList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhiteListUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "internalData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhiteListed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "launchpadAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "master", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participationCriteria",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWhiteListUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reqestedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salesFeeInPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teamVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teamVestingRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "temaVestingCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenomics", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockLPTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whiteListUsers",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class Presale extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PresaleInterface;

  functions: {
    buyTokensOnPresale(
      numOfTokensRequested: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    chageSaleType(
      _type: BigNumberish,
      _address: string,
      minimumTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimTokensOrARefund(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    contributorCycles(overrides?: CallOverrides): Promise<[BigNumber]>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
      }
    >;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber] & {
        isEnabled: boolean;
        firstReleasePC: BigNumber;
        vestingPeriodOfEachCycle: BigNumber;
        tokensReleaseEachCyclePC: BigNumber;
      }
    >;

    emergencyWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finalizePresale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getContributorsList(overrides?: CallOverrides): Promise<[string[]]>;

    getWhiteListUsers(overrides?: CallOverrides): Promise<[string[]]>;

    internalData(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        totalTokensSold: BigNumber;
        revenueFromPresale: BigNumber;
        tokensAddedToLiquidity: BigNumber;
        extraTokens: BigNumber;
        poolShareBNB: BigNumber;
        devTeamShareBNB: BigNumber;
        ownersShareBNB: BigNumber;
      }
    >;

    isWhiteListed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    launchpadAddresses(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string] & {
        pancakeSwapFactoryAddr: string;
        pancakeSwapRouterAddr: string;
        WBNBAddr: string;
        teamAddr: string;
        devAddr: string;
      }
    >;

    master(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }
    >;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, number, BigNumber, string, BigNumber, number] & {
        tokensForSale: BigNumber;
        tokensPCForLP: BigNumber;
        typeOfPresale: number;
        priceOfEachToken: BigNumber;
        criteriaToken: string;
        minTokensForParticipation: BigNumber;
        refundType: number;
      }
    >;

    presaleCounts(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        remainingTokensForSale: BigNumber;
        accumulatedBalance: BigNumber;
        contributors: BigNumber;
        claimsCount: BigNumber;
      }
    >;

    presaleInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, number] & {
        id: BigNumber;
        presaleOwner: string;
        preSaleStatus: number;
      }
    >;

    presaleTimes(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        startedAt: BigNumber;
        expiredAt: BigNumber;
        lpLockupDuration: BigNumber;
      }
    >;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    reqestedTokens(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        minTokensReq: BigNumber;
        maxTokensReq: BigNumber;
        softCap: BigNumber;
      }
    >;

    salesFeeInPercent(overrides?: CallOverrides): Promise<[number]>;

    teamVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        isEnabled: boolean;
        vestingTokens: BigNumber;
        firstReleaseTime: BigNumber;
        firstReleasePC: BigNumber;
        vestingPeriodOfEachCycle: BigNumber;
        tokensReleaseEachCyclePC: BigNumber;
      }
    >;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
        releaseStatus: number;
      }
    >;

    temaVestingCycles(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokenInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber] & {
        preSaleToken: string;
        name: string;
        symbol: string;
        decimals: BigNumber;
      }
    >;

    tokenomics(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        tokensForSale: BigNumber;
        tokensPCForLP: BigNumber;
        tokensForLocker: BigNumber;
      }
    >;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlockLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlockTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  buyTokensOnPresale(
    numOfTokensRequested: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  chageSaleType(
    _type: BigNumberish,
    _address: string,
    minimumTokens: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimTokensOrARefund(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

  contributorVestingRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      cycle: BigNumber;
      releaseTime: BigNumber;
      tokensPC: BigNumber;
      percentageToRelease: BigNumber;
    }
  >;

  contributorsVesting(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, BigNumber] & {
      isEnabled: boolean;
      firstReleasePC: BigNumber;
      vestingPeriodOfEachCycle: BigNumber;
      tokensReleaseEachCyclePC: BigNumber;
    }
  >;

  emergencyWithdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finalizePresale(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getContributorsList(overrides?: CallOverrides): Promise<string[]>;

  getWhiteListUsers(overrides?: CallOverrides): Promise<string[]>;

  internalData(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      totalTokensSold: BigNumber;
      revenueFromPresale: BigNumber;
      tokensAddedToLiquidity: BigNumber;
      extraTokens: BigNumber;
      poolShareBNB: BigNumber;
      devTeamShareBNB: BigNumber;
      ownersShareBNB: BigNumber;
    }
  >;

  isWhiteListed(_address: string, overrides?: CallOverrides): Promise<boolean>;

  launchpadAddresses(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string] & {
      pancakeSwapFactoryAddr: string;
      pancakeSwapRouterAddr: string;
      WBNBAddr: string;
      teamAddr: string;
      devAddr: string;
    }
  >;

  master(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  participant(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }>;

  participationCriteria(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, number, BigNumber, string, BigNumber, number] & {
      tokensForSale: BigNumber;
      tokensPCForLP: BigNumber;
      typeOfPresale: number;
      priceOfEachToken: BigNumber;
      criteriaToken: string;
      minTokensForParticipation: BigNumber;
      refundType: number;
    }
  >;

  presaleCounts(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      remainingTokensForSale: BigNumber;
      accumulatedBalance: BigNumber;
      contributors: BigNumber;
      claimsCount: BigNumber;
    }
  >;

  presaleInfo(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, number] & {
      id: BigNumber;
      presaleOwner: string;
      preSaleStatus: number;
    }
  >;

  presaleTimes(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      startedAt: BigNumber;
      expiredAt: BigNumber;
      lpLockupDuration: BigNumber;
    }
  >;

  removeWhiteListUsers(
    _addresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  reqestedTokens(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      minTokensReq: BigNumber;
      maxTokensReq: BigNumber;
      softCap: BigNumber;
    }
  >;

  salesFeeInPercent(overrides?: CallOverrides): Promise<number>;

  teamVesting(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      isEnabled: boolean;
      vestingTokens: BigNumber;
      firstReleaseTime: BigNumber;
      firstReleasePC: BigNumber;
      vestingPeriodOfEachCycle: BigNumber;
      tokensReleaseEachCyclePC: BigNumber;
    }
  >;

  teamVestingRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      cycle: BigNumber;
      releaseTime: BigNumber;
      tokensPC: BigNumber;
      percentageToRelease: BigNumber;
      releaseStatus: number;
    }
  >;

  temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

  tokenInfo(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber] & {
      preSaleToken: string;
      name: string;
      symbol: string;
      decimals: BigNumber;
    }
  >;

  tokenomics(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      tokensForSale: BigNumber;
      tokensPCForLP: BigNumber;
      tokensForLocker: BigNumber;
    }
  >;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlockLPTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlockTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  whiteListUsers(
    _addresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyTokensOnPresale(
      numOfTokensRequested: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    chageSaleType(
      _type: BigNumberish,
      _address: string,
      minimumTokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTokensOrARefund(overrides?: CallOverrides): Promise<void>;

    contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
      }
    >;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber] & {
        isEnabled: boolean;
        firstReleasePC: BigNumber;
        vestingPeriodOfEachCycle: BigNumber;
        tokensReleaseEachCyclePC: BigNumber;
      }
    >;

    emergencyWithdraw(overrides?: CallOverrides): Promise<void>;

    finalizePresale(overrides?: CallOverrides): Promise<void>;

    getContributorsList(overrides?: CallOverrides): Promise<string[]>;

    getWhiteListUsers(overrides?: CallOverrides): Promise<string[]>;

    internalData(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        totalTokensSold: BigNumber;
        revenueFromPresale: BigNumber;
        tokensAddedToLiquidity: BigNumber;
        extraTokens: BigNumber;
        poolShareBNB: BigNumber;
        devTeamShareBNB: BigNumber;
        ownersShareBNB: BigNumber;
      }
    >;

    isWhiteListed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    launchpadAddresses(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string] & {
        pancakeSwapFactoryAddr: string;
        pancakeSwapRouterAddr: string;
        WBNBAddr: string;
        teamAddr: string;
        devAddr: string;
      }
    >;

    master(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { value: BigNumber; tokens: BigNumber }
    >;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, number, BigNumber, string, BigNumber, number] & {
        tokensForSale: BigNumber;
        tokensPCForLP: BigNumber;
        typeOfPresale: number;
        priceOfEachToken: BigNumber;
        criteriaToken: string;
        minTokensForParticipation: BigNumber;
        refundType: number;
      }
    >;

    presaleCounts(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        remainingTokensForSale: BigNumber;
        accumulatedBalance: BigNumber;
        contributors: BigNumber;
        claimsCount: BigNumber;
      }
    >;

    presaleInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, number] & {
        id: BigNumber;
        presaleOwner: string;
        preSaleStatus: number;
      }
    >;

    presaleTimes(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        startedAt: BigNumber;
        expiredAt: BigNumber;
        lpLockupDuration: BigNumber;
      }
    >;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    reqestedTokens(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        minTokensReq: BigNumber;
        maxTokensReq: BigNumber;
        softCap: BigNumber;
      }
    >;

    salesFeeInPercent(overrides?: CallOverrides): Promise<number>;

    teamVesting(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        isEnabled: boolean;
        vestingTokens: BigNumber;
        firstReleaseTime: BigNumber;
        firstReleasePC: BigNumber;
        vestingPeriodOfEachCycle: BigNumber;
        tokensReleaseEachCyclePC: BigNumber;
      }
    >;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
        releaseStatus: number;
      }
    >;

    temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

    tokenInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber] & {
        preSaleToken: string;
        name: string;
        symbol: string;
        decimals: BigNumber;
      }
    >;

    tokenomics(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        tokensForSale: BigNumber;
        tokensPCForLP: BigNumber;
        tokensForLocker: BigNumber;
      }
    >;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unlockLPTokens(overrides?: CallOverrides): Promise<void>;

    unlockTokens(overrides?: CallOverrides): Promise<void>;

    whiteListUsers(
      _addresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    buyTokensOnPresale(
      numOfTokensRequested: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    chageSaleType(
      _type: BigNumberish,
      _address: string,
      minimumTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimTokensOrARefund(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contributorsVesting(overrides?: CallOverrides): Promise<BigNumber>;

    emergencyWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finalizePresale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getContributorsList(overrides?: CallOverrides): Promise<BigNumber>;

    getWhiteListUsers(overrides?: CallOverrides): Promise<BigNumber>;

    internalData(overrides?: CallOverrides): Promise<BigNumber>;

    isWhiteListed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    launchpadAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    master(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    participant(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    participationCriteria(overrides?: CallOverrides): Promise<BigNumber>;

    presaleCounts(overrides?: CallOverrides): Promise<BigNumber>;

    presaleInfo(overrides?: CallOverrides): Promise<BigNumber>;

    presaleTimes(overrides?: CallOverrides): Promise<BigNumber>;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    reqestedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    salesFeeInPercent(overrides?: CallOverrides): Promise<BigNumber>;

    teamVesting(overrides?: CallOverrides): Promise<BigNumber>;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

    tokenInfo(overrides?: CallOverrides): Promise<BigNumber>;

    tokenomics(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlockLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlockTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTokensOnPresale(
      numOfTokensRequested: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    chageSaleType(
      _type: BigNumberish,
      _address: string,
      minimumTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimTokensOrARefund(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    contributorCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contributorsVesting(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    emergencyWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finalizePresale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getContributorsList(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWhiteListUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    internalData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isWhiteListed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    launchpadAddresses(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    master(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    participant(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    participationCriteria(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presaleCounts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    presaleInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    presaleTimes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    reqestedTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    salesFeeInPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    teamVesting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    temaVestingCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenomics(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlockLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlockTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
