/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SalesTrackerInterface extends ethers.utils.Interface {
  functions: {
    "activeSalesCount()": FunctionFragment;
    "activeSalesList()": FunctionFragment;
    "containsActiveSale(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "activeSalesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeSalesList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "containsActiveSale",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeSalesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeSalesList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "containsActiveSale",
    data: BytesLike
  ): Result;

  events: {};
}

export class SalesTracker extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SalesTrackerInterface;

  functions: {
    activeSalesCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    activeSalesList(overrides?: CallOverrides): Promise<[string[]]>;

    containsActiveSale(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  activeSalesCount(overrides?: CallOverrides): Promise<BigNumber>;

  activeSalesList(overrides?: CallOverrides): Promise<string[]>;

  containsActiveSale(
    value: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    activeSalesCount(overrides?: CallOverrides): Promise<BigNumber>;

    activeSalesList(overrides?: CallOverrides): Promise<string[]>;

    containsActiveSale(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    activeSalesCount(overrides?: CallOverrides): Promise<BigNumber>;

    activeSalesList(overrides?: CallOverrides): Promise<BigNumber>;

    containsActiveSale(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activeSalesCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    activeSalesList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    containsActiveSale(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
