/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface VestingManagerInterface extends ethers.utils.Interface {
  functions: {
    "contributorCycles()": FunctionFragment;
    "contributorVestingRecord(uint256)": FunctionFragment;
    "teamVestingRecord(uint256)": FunctionFragment;
    "temaVestingCycles()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "contributorCycles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributorVestingRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "teamVestingRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "temaVestingCycles",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "contributorCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorVestingRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teamVestingRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "temaVestingCycles",
    data: BytesLike
  ): Result;

  events: {};
}

export class VestingManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VestingManagerInterface;

  functions: {
    contributorCycles(overrides?: CallOverrides): Promise<[BigNumber]>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
      }
    >;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
        releaseStatus: number;
      }
    >;

    temaVestingCycles(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

  contributorVestingRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      cycle: BigNumber;
      releaseTime: BigNumber;
      tokensPC: BigNumber;
      percentageToRelease: BigNumber;
    }
  >;

  teamVestingRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      cycle: BigNumber;
      releaseTime: BigNumber;
      tokensPC: BigNumber;
      percentageToRelease: BigNumber;
      releaseStatus: number;
    }
  >;

  temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
      }
    >;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        cycle: BigNumber;
        releaseTime: BigNumber;
        tokensPC: BigNumber;
        percentageToRelease: BigNumber;
        releaseStatus: number;
      }
    >;

    temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    contributorCycles(overrides?: CallOverrides): Promise<BigNumber>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    temaVestingCycles(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    contributorCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contributorVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    teamVestingRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    temaVestingCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
