/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface WhitelistManagerInterface extends ethers.utils.Interface {
  functions: {
    "getWhiteListUsers()": FunctionFragment;
    "getWhiteListUsersCount()": FunctionFragment;
    "isWhiteListed(address)": FunctionFragment;
    "removeWhiteListUsers(address[])": FunctionFragment;
    "whiteListUsers(address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getWhiteListUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWhiteListUsersCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isWhiteListed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWhiteListUsers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "whiteListUsers",
    values: [string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getWhiteListUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhiteListUsersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhiteListed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWhiteListUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whiteListUsers",
    data: BytesLike
  ): Result;

  events: {};
}

export class WhitelistManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: WhitelistManagerInterface;

  functions: {
    getWhiteListUsers(overrides?: CallOverrides): Promise<[string[]]>;

    getWhiteListUsersCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    isWhiteListed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getWhiteListUsers(overrides?: CallOverrides): Promise<string[]>;

  getWhiteListUsersCount(overrides?: CallOverrides): Promise<BigNumber>;

  isWhiteListed(_address: string, overrides?: CallOverrides): Promise<boolean>;

  removeWhiteListUsers(
    _addresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  whiteListUsers(
    _addresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getWhiteListUsers(overrides?: CallOverrides): Promise<string[]>;

    getWhiteListUsersCount(overrides?: CallOverrides): Promise<BigNumber>;

    isWhiteListed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    whiteListUsers(
      _addresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getWhiteListUsers(overrides?: CallOverrides): Promise<BigNumber>;

    getWhiteListUsersCount(overrides?: CallOverrides): Promise<BigNumber>;

    isWhiteListed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getWhiteListUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWhiteListUsersCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhiteListed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeWhiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    whiteListUsers(
      _addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
